[build]
  command = "npm run build"
  publish = "dist/angular-portfolio"

[build.environment]
  NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
